---
- name: Playbook to provision vm as a raspbian sd card formatter

  hosts: all
  roles:
    - role: bassinator.guest_additions
      virtualbox_version: 6.0.4
    # - { role: centos.sd-formatter }
    - { role: bassinator.pi_reset }
